version: "3"

services:
  selenium:
    image: selenium/standalone-firefox
    ports:
      - 4444:4444
  test:
    build: .
    depends_on:
      - "selenium"
    command: sh -c 'sleep 3 && pytest'
    volumes:
      - .:/code